module.exports.decorativePlasterDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      type: "decorativePlaster1",
      customSquare: 0,
      density: 3,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Декоративная  штукатурка",
      name: "Декоративная  штукатурка Короед 2, 25кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "decorativePlaster2",
      customSquare: 0,
      density: 4,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Декоративная  штукатурка",
      name: "Декоративная  штукатурка Короед 3, 25кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 2,
      measure:"кг",
      type: "decorativePlaster3",
      customSquare: 0,
      density: 2,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Декоративная  штукатурка",
      name: "Декоративная  штукатурка Шуба 1, 25кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 3,
      measure:"кг",
      type: "decorativePlaster4",
      customSquare: 0,
      density: 3,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Декоративная  штукатурка",
      name: "Декоративная  штукатурка Шуба 2, 25кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 4,
      measure:"кг",
      type: "decorativePlaster5",
      customSquare: 0,
      density: 4,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Декоративная  штукатурка",
      name: "Декоративная  штукатурка Шуба 3, 25кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 5,
      measure:"кг",
      type: "decorativePlaster6",
      customSquare: 0,
      density: 3,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "Декоративная  штукатурка",
      name: "MIX BEST Декоративная штукатурка ШУБА, 20кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    }
  ];
};

module.exports.mixBestDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      type: "mixBest1",
      customSquare: 0,
      density: 5,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "MIX BEST",
      name: "MIX BEST Клей для теплоизоляции универсальный, 20кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "mixBest2",
      customSquare: 0,
      density: 5,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "MIX BEST",
      name: "MIX BEST Декоративная штукатурка ШУБА, 20кг",
      thickness: "-",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 2,
      measure:"кг",
      type: "mixBest3",
      customSquare: 0,
      density: 1.45,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "MIX BEST",
      name: "MIX BEST Смесь цементно-песчаная, 20кг",
      thickness: "более 3",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 3,
      measure:"кг",
      type: "mixBest4",
      customSquare: 0,
      density: 1.4,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "MIX BEST",
      name: "MIX BEST Клей плиточный базовый, 20кг",
      thickness: "3-10",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    }
  ];
};

module.exports.mixLKMDefault = () => {
  return [
    {
      idInn: 0,
      measure:"л.",
      type: "mixLKM1",
      customSquare: 0,
      density: 0.125,
      weight: 5,
      resultCalc: 0,
      need: 0,
      text: "ЛКМ",
      name: "Грунт глубокого проникновения акриловый универсальный, 5л",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "канистр"
    },
    {
      idInn: 1,
      measure:"кг",
      type: "mixLKM2",
      customSquare: 0,
      density: 0.275,
      weight: 6,
      resultCalc: 0,
      need: 0,
      text: "ЛКМ",
      name: "Кварц-грунт (бетоноконтакт) 6кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "ведро"
    },
    {
      idInn: 2,
      measure:"кг",
      type: "mixLKM3",
      customSquare: 0,
      density: 0.2,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "ЛКМ",
      name: "Краска фасадная, 20кг (один слой)",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "ведро"
    },
    {
      idInn: 3,
      measure:"кг",
      type: "mixLKM4",
      customSquare: 0,
      density: 0.35,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "ЛКМ",
      name: "Краска фасадная, 20кг (два слоя)",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "ведро"
    }
  ];
};
module.exports.cementPlasterDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      type: "cementPlaster1",
      customSquare: 0,
      density: 1.4,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Цементная штукатурка и шпатлевка",
      name: "Пласт, 25кг (Штукатурка)",
      thickness: "2-20",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "cementPlaster2",
      customSquare: 0,
      density: 0.9,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "Цементная штукатурка и шпатлевка",
      name: "Пласт-Финиш, 20кг  (Шпатлевка)",
      thickness: "1-6",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    }
  ];
};
module.exports.mixForFloorDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      type: "mixForFloor1",
      customSquare: 0,
      density: 1.3,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Смесь для устройства пола",
      name: "Идеал, 25кг (Наливной пол)",
      thickness: "2-10",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "mixForFloor2",
      customSquare: 0,
      density: 1.5,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Смесь для устройства пола",
      name: "Конкрет, 25 кг (Стяжка для пола)",
      thickness: "5-80",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    }
  ];
};
module.exports.gypsumPlasterDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      customSquare: 0,
      type: "gypsumPlaster1",
      density: 1.25,
      weight: 30,
      resultCalc: 0,
      need: 0,
      text: "Гипсовая штукатурка",
      name: "Пласт Гипс, 30кг",
      thickness: "2-80мм",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "gypsumPlaster2",
      customSquare: 0,
      density: 1,
      weight: 30,
      resultCalc: 0,
      need: 0,
      text: "Гипсовая штукатурка",
      name: "Пласт Гипс Тонкий, 30кг",
      thickness: "2-20мм",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    }
  ];
};
module.exports.mountingMixturesDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      type: "mountingMix1",
      density: 1.4,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name: "Техно, 25 кг (Клей для кладки блоков)",
      thickness: "3-10мм",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "mountingMix2",
      customSquare: 0,
      density: 1.5,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name: "Пескобетон М-300, 25кг",
      thickness: "более 3мм",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 2,
      measure:"кг",
      type: "mountingMix3",
      customSquare: 0,
      density: 1.45,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name: "Цементно песчанная смесь М-150, 25кг",
      thickness: "более 3мм",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 3,
      measure:"кг",
      type: "mountingMix4",
      customSquare: 0,
      density: 5,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name: "КТП 500, 25кг (Клей для приклеивания теплоизоляции)",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 4,
      measure:"кг",
      type: "mountingMix5",
      customSquare: 0,
      density: 5,
      weight: 25,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name:
        "КТУ 1000, 25кг (Клей для приклеивания и армирования теплоизоляции)",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 5,
      measure:"кг",
      type: "mountingMix6",
      customSquare: 0,
      density: 5,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name: "MIX BEST Клей для теплоизоляции универсальный, 20кг",
      thickness: "-",
      inputThickness: false,
      customThickness: 1,
      unit: "меш."
    },
    {
      idInn: 6,
      measure:"кг",
      type: "mountingMix7",
      customSquare: 0,
      density: 1.45,
      weight: 20,
      resultCalc: 0,
      need: 0,
      text: "Кладочно-монтажная смесь",
      name: "MIX BEST Смесь цементно-песчаная, 20кг",
      thickness: "более 3мм",
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    }
  ];
};
module.exports.tileAdhesiveDefault = () => {
  return [
    {
      idInn: 0,
      measure:"кг",
      type: "tileAdhesive1",
      text: "Плиточный клей",
      name: "Плиточный клей Стандарт, 25кг",
      thickness: "3-10мм",
      customSquare: 0,
      density: 1.4,
      weight: 25,
      resultCalc: 0,
      need: 0,
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 1,
      measure:"кг",
      type: "tileAdhesive2",
      text: "Плиточный клей",
      name: "Плиточный клей Гранит, 25кг",
      thickness: "3-10мм",
      density: 1.45,
      customSquare: 0,
      weight: 25,
      resultCalc: 0,
      need: 0,
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 2,
      measure:"кг",
      type: "tileAdhesive3",
      text: "Плиточный клей",
      name: "Плиточный клей Профи, 25кг",
      thickness: "3-10мм",
      density: 1.35,
      customSquare: 0,
      weight: 25,
      resultCalc: 0,
      need: 0,
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    },
    {
      idInn: 3,
      measure:"кг",
      type: "tileAdhesive4",
      text: "Плиточный клей",
      name: "MIX BEST Клей плиточный базовый, 20кг",
      thickness: "3-10мм",
      customSquare: 0,
      density: 1.4,
      weight: 20,
      resultCalc: 0,
      need: 0,
      inputThickness: true,
      customThickness: 0,
      unit: "меш."
    }
  ];
};
